version: '1.0'
services:
  api:
    build: .
    container_name: teste-mepoupe
    restart: always
    environment:
      DB_HOST: db
      DB_DATABASE: teste_fullstack
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: teste_fullstack
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306
